# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_login_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UILoginWidget(object):
    def setupUi(self, UILoginWidget):
        UILoginWidget.setObjectName("UILoginWidget")
        UILoginWidget.resize(811, 450)

        self.retranslateUi(UILoginWidget)
        QtCore.QMetaObject.connectSlotsByName(UILoginWidget)

    def retranslateUi(self, UILoginWidget):
        _translate = QtCore.QCoreApplication.translate
        UILoginWidget.setWindowTitle(_translate("UILoginWidget", "Form"))
