# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_vital_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UIVitalWidget(object):
    def setupUi(self, UIVitalWidget):
        UIVitalWidget.setObjectName("UIVitalWidget")
        UIVitalWidget.resize(811, 450)

        self.retranslateUi(UIVitalWidget)
        QtCore.QMetaObject.connectSlotsByName(UIVitalWidget)

    def retranslateUi(self, UIVitalWidget):
        _translate = QtCore.QCoreApplication.translate
        UIVitalWidget.setWindowTitle(_translate("UIVitalWidget", "Form"))
